export const tags = [
  { name: '每日一文', url: 'guanzhi', active: false },
  { name: '腾讯大家', url: 'dajia', active: false },
  { name: 'ONE · 一个', url: 'one', active: false },
  { name: '爱思想', url: 'aisixiang/ranking/1/7', active: false },
  { name: 'Poems', url: 'allpoetry/newest', active: false },
  { name: '古诗文网', url: 'gushiwen/recommend', active: false },
  { name: '喷嚏图卦', url: 'dapenti/tugua', active: false },
  { name: '刷屏 · 最新', url: 'weseepro/newest', active: false },
  { name: '虎扑', url: 'hupu/bbs/bxj/2', active: false },
  {
    name: 'Dcard',
    url: 'dcard/posts/popular',
    child: { popular: '热门', latest: '最新' },
    active: false,
  },
  {
    name: 'Dribbble',
    url: 'dribbble/popular/week',
    child: {
      week: '周',
      month: '月',
      year: '年',
      ever: '一直',
    },
    active: false,
  },
  {
    name: '站酷',
    url: 'zcool/recommend/all',
    child: {
      home: '首页推荐',
      edit: '编辑推荐',
      all: '全部推荐',
    },
    active: false,
  },
  // { name: 'Matters', url: 'matters/hot', active: false },
  {
    name: 'bilibili排行榜',
    url: 'bilibili/ranking/0/3',
    active: false,
  },
  { name: '好奇怪', url: 'qdaily/notch/posts', active: false },
  { name: '知乎热点', url: 'zhihu/hotlist', active: false },
  { name: '知乎日报', url: 'zhihu/daily', active: false },
  { name: '知乎想法热榜', url: 'zhihu/pin/hotlist', active: false },
  { name: '知乎周刊', url: 'zhihu/weekly', active: false },
  { name: '简书周榜', url: 'jianshu/trending/weekly', active: false },
  {
    name: '豆瓣热门图书',
    url: 'douban/book/rank/fiction',
    child: { fiction: '虚构', nonfiction: '非虚构' },
    active: false,
  },

  { name: '豆瓣电影', url: 'douban/movie/playing', active: false },
  { name: '微博热搜', url: 'weibo/search/hot', active: false },
  { name: '电影首发站', url: 'dysfz', active: false },
  { name: '电影天堂', url: 'dytt', active: false },
  { name: '开眼', url: 'kaiyan/index', active: false },
  { name: '故事 FM', url: 'storyfm/index', active: false },
  { name: '煎蛋', url: 'jandan/top', active: false },
  { name: 'Awesome Pigtails', url: 'pigtails/index', active: false },
  { name: '马蜂窝', url: 'mafengwo/note/hot', active: false },
  { name: '国家地理每日一图', url: 'natgeo/dailyphoto', active: false },
  { name: '中国美术馆', url: 'namoc/announcement', active: false },
  { name: '懂球帝', url: 'dongqiudi/daily', active: false },
  { name: '谷歌学术', url: 'google/scholar/data+visualization', active: false },
  {
    name: 'github-Trending',
    url: 'github/trending/dayily/javascript',
    child: {
      javascript: 'javascript',
      css: 'css',
      html: 'html',
      dart: 'dart',
      java: 'java',
    },
    active: false,
  },
  { name: 'GitLab', url: 'gitlab/explore/trending', active: false },
  { name: 'V2EX', url: 'v2ex/topics/hot', active: false },
  { name: 'GitChat', url: 'gitchat/newest', active: false },
  { name: '技术头条', url: 'blogread/newest', active: false },
  { name: '开发者头条', url: 'toutiao/today', active: false },
  { name: '开源中国', url: 'oschina/news', active: false },
  { name: '前端艺术家', url: 'jskou/0', active: false },
  { name: '下厨房', url: 'xiachufang/popular/week', active: false },
  { name: '好物推荐', url: 'smzdm/ranking/pinlei/11/10', active: false },
  { name: '礼物说', url: 'liwushuo/index', active: false },
  { name: '小米有品众筹', url: 'mi/crowdfunding', active: false },
  { name: '探物', url: 'tanwu/products', active: false },
  { name: '龙空', url: 'lkong/forum/60', active: false },
  { name: '澎湃新闻', url: 'thepaper/featured', active: false },
  { name: '3DMGAME', url: '3dm/news', active: false },
  { name: '游民星空今日推荐', url: 'gamersky/news', active: false },
  { name: '妹子图', url: 'mzitu/home', active: false },
  {
    name: 'pixiv',
    url: 'pixiv/ranking/week',
    child: {
      day: '日排行',
      week: '周排行',
      month: '月排行',
      week_r18: 'r18排行',
    },
    active: false,
  },
];

export const tagColor = [
  'is-primary',
  'is-warning',
  'is-link',
  'is-info',
  'is-success',
  'is-danger',
  // 'is-light',
];
