// { name: '', url: '', active: false},
// eslint-disable-next-line
export const tags = [
  { name: '每日一文', url: 'guanzhi', active: false },
  { name: '腾讯大家', url: 'dajia', active: false },
  { name: '澎湃新闻', url: 'thepaper/featured', active: false },
  { name: '南方周末', url: '/infzm/0', active: false },
  { name: '纽约时报', url: 'nytimes', active: false },
  { name: '联合早报', url: 'zaobao/realtime/china', active: false },
  { name: '刷屏 · 最新', url: 'weseepro/newest', active: false },
  { name: '开发者头条', url: 'toutiao/today', active: false },
  { name: '开源中国', url: 'oschina/news', active: false },
  { name: '技术头条', url: 'blogread/newest', active: false },
  { name: 'GitLab', url: 'gitlab/explore/trending', active: false },
  { name: '好物推荐', url: 'smzdm/ranking/pinlei/11/10', active: false },
  { name: '探物', url: 'tanwu/products', active: false },
  { name: 'bilibili排行榜', url: 'bilibili/ranking/0/3', active: false },
  { name: '即刻', url: 'jike/daily', active: false },
  { name: '知乎热点', url: 'zhihu/hotlist', active: false },
  { name: '知乎日报', url: 'zhihu/daily', active: false },
  { name: '简书', url: 'jianshu/trending/weekly', active: false },
  { name: '豆瓣新书', url: 'douban/book/latest', active: false },
  { name: '豆瓣电影', url: 'douban/movie/playing', active: false },
  { name: '电影首发站', url: 'dysfz', active: false },
  { name: '电影天堂', url: 'dytt', active: false },
  { name: '微博热搜', url: 'weibo/search/hot', active: false },
  { name: '煎蛋', url: 'jandan/top', active: false },
  { name: '喷嚏图卦', url: 'dapenti/tugua', active: false },
  { name: '马蜂窝', url: 'mafengwo/note/hot', active: false },
  { name: '国家地理', url: 'natgeo/news/ngnews', active: false },
  { name: '中国美术馆', url: 'namoc/announcement', active: false },
  { name: 'ONE · 一个', url: 'one', active: false },
  { name: '懂球帝', url: 'dongqiudi/daily', active: false },
  { name: '谷歌学术', url: 'google/scholar/data+visualization', active: false },
  { name: '下厨房', url: 'xiachufang/popular/week', active: false },
  { name: '妹子图', url: 'mzitu/home', active: false },
  { name: 'JavBus', url: 'javbus/home', active: false },
  { name: 'nhentai', url: 'nhentai/language/chinese', active: false },
];

// eslint-disable-next-line
export const tagColor = [
  'is-primary',
  'is-warning',
  'is-link',
  'is-info',
  'is-success',
  'is-danger',
  // 'is-light',
];
